[versions]
micronaut-docs = "2.0.0"
micronaut = "4.0.0"
micronaut-test = "4.0.0"

groovy = "4.0.12"
spock = "2.3-groovy-4.0"

cache-ri-impl = "1.1.1"
managed-caffeine = "3.1.7"
managed-ehcache = "3.10.8"
managed-hazelcast = "5.3.1"
managed-infinispan = "14.0.12.Final"
managed-jcache = "1.1.1"

micronaut-micrometer = "5.0.1"
micronaut-serde = "2.0.1"
micronaut-validation = "4.0.1"
testcontainers = "1.18.3"
graal-svm = "23.0.1"

micronaut-logging = "1.0.0"
[libraries]
# Core
micronaut-core = { module = 'io.micronaut:micronaut-core-bom', version.ref = 'micronaut' }

# Managed
managed-caffeine = { module = "com.github.ben-manes.caffeine:caffeine", version.ref = "managed-caffeine" }
managed-hazelcast = { module = "com.hazelcast:hazelcast", version.ref = "managed-hazelcast" }
managed-ehcache-clustered = { module = "org.ehcache:ehcache-clustered", version.ref = "managed-ehcache" }
managed-ehcache = { module = "org.ehcache:ehcache", version.ref = "managed-ehcache" }
managed-infinispan-client-hotrod = { module = "org.infinispan:infinispan-client-hotrod", version.ref = "managed-infinispan" }
managed-infinispan-core = { module = "org.infinispan:infinispan-core", version.ref = "managed-infinispan" }
managed-jcache = { module = "javax.cache:cache-api", version.ref = "managed-jcache" }

micronaut-micrometer = { module = "io.micronaut.micrometer:micronaut-micrometer-bom", version.ref = "micronaut-micrometer" }
micronaut-serde = { module = "io.micronaut.serde:micronaut-serde-bom", version.ref = "micronaut-serde" }
micronaut-validation = { module = "io.micronaut.validation:micronaut-validation-bom", version.ref = "micronaut-validation" }

cache-api = { module = "javax.cache:cache-api", version.ref = "cache-ri-impl" }
cache-ri-impl = { module = "org.jsr107.ri:cache-ri-impl", version.ref = "cache-ri-impl" }
testcontainers-spock = { module = "org.testcontainers:spock", version.ref = "testcontainers" }
graal-svm = { module = "org.graalvm.nativeimage:svm", version.ref = "graal-svm" }
spock-core = { module = "org.spockframework:spock-core", version.ref = "spock" }
