[versions]
cache-ri-impl = "1.1.1"
managed-caffeine = "2.9.3"
managed-ehcache = "3.8.1"
managed-hazelcast = "4.2.5"
managed-infinispan = "14.0.0.Dev04"

[libraries]
# Managed
managed-caffeine = { module = "com.github.ben-manes.caffeine:caffeine", version.ref = "managed-caffeine" }
managed-hazelcast = { module = "com.hazelcast:hazelcast", version.ref = "managed-hazelcast" }
managed-ehcache-clustered = { module = "org.ehcache:ehcache-clustered", version.ref = "managed-ehcache" }
managed-infinispan-client-hotrod = { module = "org.infinispan:infinispan-client-hotrod", version.ref = "managed-infinispan" }
managed-infinispan-core = { module = "org.infinispan:infinispan-core", version.ref = "managed-infinispan" }

# Micronaut
micronaut-aop = { module = "io.micronaut:micronaut-aop" }
micronaut-http = { module = "io.micronaut:micronaut-http" }
micronaut-http-client = { module = "io.micronaut:micronaut-http-client" }
micronaut-http-server-netty = { module = "io.micronaut:micronaut-http-server-netty" }
micronaut-inject = { module = "io.micronaut:micronaut-inject" }
micronaut-inject-groovy = { module = "io.micronaut:micronaut-inject-groovy" }
micronaut-inject-java = { module = "io.micronaut:micronaut-inject-java" }
micronaut-management = { module = "io.micronaut:micronaut-management" }
micronaut-runtime = { module = "io.micronaut:micronaut-runtime" }
micronaut-test-spock = { module = "io.micronaut.test:micronaut-test-spock" }

cache-api = { module = "javax.cache:cache-api" }
cache-ri-impl = { module = "org.jsr107.ri:cache-ri-impl", version.ref = "cache-ri-impl" }
logback-classic = { module = "ch.qos.logback:logback-classic" }
reactor-core = { module = "io.projectreactor:reactor-core" }
testcontainers-spock = { module = "org.testcontainers:spock" }
spock-core = { module = "org.spockframework:spock-core" }